# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for ScreenshotOne MCP Server

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production dependencies
COPY package.json package-lock.json ./
# Install only production deps
RUN npm install --omit=dev
COPY --from=builder /app/build ./build

# Default command
CMD ["node", "build/index.js"]
